export const productlist = [
    {
      id: 1,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 2,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 3,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 4,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 5,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 6,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 7,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 8,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 9,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 10,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 11,
      name: "NIKE AIR Zoom Tempo Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
    {
      id: 12,
      name: "NIKE AIR Zoom Tempo hoho Next% Mens Running Shoes",
      description: "mens running windrunner jacket",
      price: 5,
      img: "",
    },
  ];